### ISSUE TITLE
Strong objection against section 3.1 of the proposed Charter

### ISSUE THREAD

**Issue by therealglazou** [w3c/dpubwg-charter#12]
I am **strongly** objecting against section 3.1 of the proposed Charter that reads:

> EPUB4:     This specification defines a profile of Packaged Web Publications that delivers a higher degree of comprehensive accessibility capabilities and reliability. This specification should be as close as possible to a strict functional superset of EPUB 3.1, with incompatibilities minimized.

This is a way of locking innovation/disruption and pushes the future WG on a path that is not even discussed with its future membership. Furthermore, EPUB 3.1 and its proprietary XML formats is not Web-compatible and one of the main goals of this WG is to bridge the gap between Web and Ebooks.

**Comment by astearns** [comment]
I agree. The discussions in the interest group have been useful precisely because we have been considering the requirements of web publications without reference to EPUB compatibility. 

Including EPUB4 as a deliverable for the working group will have three pernicious effects:

- It will bias discussions of web publications towards EPUB solutions. We should be looking for web-centric solutions for the requirements presented.
- It will divide the focus of the group. If an EPUB4 profile is needed at all, it should be done in the CG tasked with maintaining EPUB 3.1.
- As stated, it reserves "a higher degree of comprehensive accessibility capabilities and reliability" to the profile. These should be folded in to web publications, not diverted into a profile.

**Comment by dauwhe** [comment]
Although I've certainly been guilty of speculating about profiles, I don't think we want a foundational assumption that profiles of web publications will be required. It may be a logical outcome of the working group's process, but I would prefer that to be proven, not assumed.

**Comment by GarthConboy** [comment]
Well, at least somewhat disagree.  :-)

First I'll start where where I agree -- that would be with the statement above "As stated, it reserves "a higher degree of comprehensive accessibility capabilities and reliability" to the profile. These should be folded in to web publications, not diverted into a profile."

Now where I disagree, as part of the "merger" of the IDPF into W3C the future of EPUB would get on the rec-track via work by the DPUB WG.  I think this fits in well with our discussions in Lisbon -- the bifurcation of PWP into "P" and "WP" -- initial focus will certainly be (rightly) on the WP portion.  There may be multiple "P"s -- but there must one serialization/profile of WP that is "EPUB 4" -- level of compatibility with EPUB 3.x TBD -- but I hope that high degree of round-trip-ability is a high priority.

**Comment by astearns** [comment]
@GarthConboy "the future of EPUB would get on the rec-track via work by the DPUB WG" - could you provide a reference for this? I haven't been following everything about the merger, but have only seen the commitment to maintaining the current version of EPUB

**Comment by lrosenthol** [comment]
@astearns It's from the agreement that the IDPF and W3C entered into, which **only** allows former IDPF members to join this particular WG (and no others).  Since EPUB 4 will be built on top of (P)WP, it means that (P)WP work and EPUB 4 work have to take place in the same WG.   And even if you were to be able to split them - you'd end up with almost 100% identical memberships.

**Comment by lrosenthol** [comment]
@dauwhe Actually, Dave, we **do** want profiles as a foundational design goal.  And as @GarthConboy said, EPUB 4 is just one of those profiles and it is compatible (for some definition of compatible) with EPUB 3.x.

As I think I said in email. I agree that the reliability piece should indeed go into the (P)WP statement and not EPUB 4.  As to the accessibility stuff, I think that is being worked out well in the sub-group (as discussed on the call yesterday)

**Comment by iherman** [comment]
(Admin: Copying, with his permission, the response of Gregg Vanderheiden on the same issue raised by Daniel on the AC forum mailing list. Doing this just to have all the arguments at one place.



> Hi Daniel
>
> I think that there is a place for disruption and a place for compatibility.   Compatibility is one of the key factors in creating standards.
>
> A completely new publication format can always be proposed that is disruptive.    And they often are.
>
>But for something to be EPUB 4  that breaks EPUB 3 without a  very good reason — does not sound like good standards making.
>
> NOTE that the language of 3.1 does not preclude innovation or disruption
>
>It states   “as close as possible”   and  “incompatibilities minimized”
>
>>This specification should be as close as possible to a strict functional superset of EPUB 3.1, with incompatibilities minimized.
>
>Neither of these prevents things from being disruptive for a good reason.   But if a whole new or disruptive approach is desired - it is probably best done as a new standard - so that it is truly free to innovate and disrupt.  Trying to use an existing standard for a disruptive new standard is not usually the best path and will lead to much argument, public comments to be cleared, and delay in moving something forward.
>
>I am all for starting with a fresh slate — or forking the code and tossing the past in favor of a new approach.  But I don’t usually want to disrupt by tearing up the road people are traveling on.  I rather like to create a new road and then have them switch to it when it is ready and they are able.  
>
>Did you have something in mind for this new standard?  or are you just speaking generally in favor of the value of disruptive innovation?
>
>thanks
>
>
>gregg
>--------------------------------------------------------
>Gregg Vanderheiden Ph.D.
>Director, Trace R&D Center
>Professor, School of Information Studies
>University of Maryland - College Park

**Comment by therealglazou** [comment]
thank you @iherman

**Comment by therealglazou** [comment]
In response to Gregg:

1. first, no, "Compatibility is (not) one of the key factors in creating standards". I remind you that EPUB 3.0.1 is incompatible with EPUB 2, that EPUB 3.1 is mostly incompatible (at least in metadata) with EPUB 3.0.1. I implemented all three in my editor BlueGriffon and I know too well how they are incompatible. They're so incompatible that translating a given ebook from an EPUB version to another one can be extremely hard to achieve automatically and will almost always require manual tweaking. Reading Systems have to implement (on the EPUB side) three different parsers and Object Models because EPUB is **not** backwards-compatible nor forwards-compatible.

1. one of our famous says in Standardization is « a Standard is a Standard until a new Standard replaces it and then it's a Standard again ».

1. I have no idea what it means in terms of compatibility to have "incompatibilities minimized" and I'm an application developer. From a User's perspective, the various stages of the Standard are compatible or they are not. It's a strict boolean. For EPUB, that value is clearly `false`.

1. yes, I do have [something in mind](http://www.glazman.org/weblog/dotclear/index.php?post/2017/01/17/E0) for a new ebook Standard. I have not seen any proof that a EPUB4 based on the EPUB3 lineage is desireable or even required by the industry at this stage. On the contrary, I have received alarming signals from some members of the Industry letting me know they can hardly deal with EPUB 3.1 before probably 2018. On another hand, I know too well that EPUB is kind of a failure in production chains. The software landscape of EPUB, if you except distribution channels, is non-existent because of the complexity of EPUB and its lack of web-centricity. All publishers, I repeat all, rely on manual review/tweaks, Invented-Here software and black magic. This is suboptimal to a point I can hardly express.

Hth.

**Comment by dauwhe** [comment]
@lrosenthol wrote:

>Actually, Doug, we do want profiles as a foundational design goal. 

Why? A profile is a baby fork. It's complexity, and I think it needs to be justified rather than assumed.

**Comment by lrosenthol** [comment]
@dauwhe No idea how I got Doug there - sorry!!

A profile isn't a fork, at least in my mind.  A fork (to me at least) implies breaking changes.  A profile, on the other hand, means that the concepts, techniques, etc. are applied in a different context.

The justification is that there is a desire to apply the concepts of a WP or PWP in multiple workflows, that may not all use the same packaging or syntax.  For example, WP may define that a manifest contain a list of constituent resources.  The actual syntax of how that list is encoded can be left to specific profiles - since some may prefer JSON, others XML, and others some binary encoding.

If you look at what is happening over in [web packaging](https://github.com/dimich-g/webpackage), they are still trying to determine whether to use a text-based or binary-based package. And that package may not be the same one that EPUB 4 chooses to use.   But wouldn't it be great if they both used the same manifest?  

Hence profiles!

**Comment by lrosenthol** [comment]
@dauwhe Dave - the other reasons for profiles **and** for making EPUB 4 separate from (P)WP is to address one of the items that @therealglazou raises.  EPUB is an excellent standard for eBooks - with many aspects that are very specific to that industry.  However, those same aspects make it difficult or impossible to use it in other document uses - things we identified as [use cases for PWP](https://github.com/w3c/dpub-pwp-ucr).   So we might need something that isn't EPUB 4 to address them, and having a base spec and profiles enables that.

**Comment by therealglazou** [comment]
@lrosenthol EPUB is such an excellent standard for ebooks that the software ecosystem for it is zilch, if you except publishing servers and reading systems. And conformance of reading systems to the Standard is so weak it's laughable. For RSs, an EPUB is a zip of a ToC and spine and some content documents. They validate nothing, they don't respect the prose of the Standard, they don't respect error handling, they don't respect so many things that editing environments have to deal with their weaknesses. I cannot call that "excellent", sorry.

**Comment by therealglazou** [comment]
Please all (including myself), this issue is solely about the prose for EPUB 4 being forced to be "a strict functional superset of EPUB 3.1, with incompatibilities minimized" and I suggest we don't go beyond here. If you want to open extra issues on other topics or the Charter in general, feel free to do it.

**Comment by GarthConboy** [comment]
I would not be unhappy with replacing:

"a strict functional superset of EPUB 3.1, with incompatibilities minimized"

With:

"generally a functional superset of EPUB 3.1, with round-tripping to/from EPUB 3.1 considered highly desirable"

We do need to assure that the EPUB 4 serialization is a place that the publishing industry can move forward to (from EPUB 3.1) -- likely years out, as EPUB 3.1 adoption is still clearly in a ramp-up phase.

And, Daniel, just noticed "thereal" as the lead of your W3C ID!  :-)

**Comment by lrosenthol** [comment]
I don't think you need "generally" at the beginning...but otherwise, works
for me.

**Comment by GarthConboy** [comment]
Thanks Leonard!

I just included "generally" to imply that we don't intend to require a full/complete superset -- I could see some EPUB 3.1 features getting deprecated with prejudice... as in not available at all in EPUB 4.  (and no, not gonna cough up that list now!  :-).

**Comment by therealglazou** [comment]
@GarthConboy I raised the issue and I don't think I ever said I am happy with that proposal. UPDATE: did I misunderstand? Your prose juste above sounds like you did make the edit...

**Comment by GarthConboy** [comment]
Nope -- just was making a proposal on this issue -- no edit yet.   (and don't think I implied that you (Daniel) were happy with it, though I can hope!)

**Comment by GarthConboy** [comment]
As discussed at the March 13th DPUB BG meeting, and agreed there, is this following replacement for EPUB 4 in section 3.1:

EPUB 4: “This specification defines a functional profile of the general idea of Packaged Web Publications that may deliver a higher degree of comprehensive accessibility capabilities and reliability.  This specification should generally be a functional superset of EPUB 3.1, with functionally round-tripping to/from EPUB 3.1 considered highly desirable.”

**Comment by llemeurfr** [comment]
After reading again this complex and still "fuzzy" sentence, may I propose an alternative?

EPUB 4: “This specification defines a specialization of the model defined by Packaged Web Publications, that may deliver a higher degree of comprehensive accessibility capabilities and reliability. EPUB 4 should generally be a functional superset of EPUB 3.1 and functional round-tripping to/from EPUB 3.1 is highly desirable.”

**Comment by iherman** [comment]
Hm... I am not sure. The difference, as I see it, is to refer to "specialization" instead of "profile".

Although we do not yet have a clear definition of what we mean by profiling, I believe the term "profile" is more widely used in our world for what we think we have in mind, ie, turning "SHOULD" into "MUST" for some features, or restricting the set of tags that one could use. "Specialization", at least in my mind, seems to allow for more radical changes like a change of an algorithm v.a.v. the general case, which I do not think we would do.

We also have precedences for the term "profile". We did speak about an EDUPUB Profile; we did have, in the early days SVG "profiles" for mobile (SVG Tiny or SVG Basic), etc. I would prefer to keep to those...

**Comment by llemeurfr** [comment]
Re EDUPUB (a "profile" of EPUB 3.01), an issue is that this is more a kind of extension rather than a restriction, if we consider the addition of annotations, scriptable components, distributable objects, QTI, LTI, Caliper Analytics. I know that only http://www.idpf.org/epub/profiles/edu/spec/ is defined as a profile, but the term is still now a bit fuzzy. 
But I don't mind if "profile" is kept instead of "specialization", or my proposal is not retained: it is a minor point in the charter.

**Comment by lrosenthol** [comment]
i agree that we should keep profile - at least for the purpose of the
charter.

**Comment by WSchindler** [comment]
I prefer "profile" to "specialization" because this terms in my opinion better conveys that EPUB4  should be on the same level as a PWP and not just be a special (edge) case of a PWP. Achieving a common technical basis for web publishing (online and offline), apps and printed books with options to cater for the specific requirements of each channel would be a great step :)

**Comment by lrosenthol** [comment]
Actually Wolfgang, the point of a profile is that it will be related to but
not the same as.
